name: inventory_scanner
description: Ứng dụng kiểm kho - quét mã vạch, so sánh với tồn lý thuyết từ Excel/CSV.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  excel: ^4.0.6
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
